language: python


matrix:
  include:
    - name: "ubuntu xenial"
      os: linux  
      dist: xenial
    - name: "ubuntu bionic"
      os: linux
      dist: bionic

python:
  - "3.6"

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh							 
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION snakemake ncbi-genome-download r-base r-argparse r-curl r-data.table r-dplyr
  - conda list
  - wget http://ftp.tue.mpg.de/ebio/projects/struo/misc/uniref50.ec_filtered.1.1.dmnd

script:
  - snakemake --use-conda --configfile tests/config.yaml
