#-- I/O --#
# file listing samples and associated data
samples_file: tests/samples/samples_n10.txt

## column names in samples table
samples_col: 'ncbi_organism_name'
fasta_file_path_col: 'fasta_file_path'
taxID_col: 'ncbi_species_taxid'
taxonomy_col: 'ncbi_taxonomy'

# output location
output_dir: /ebio/abt3_projects/software/dev/data/llmgp-db_n10/

#-- databases to create --#
# Replace "Create" with "Skip" to skip creation of any of these
# Note that braken relies on the kraken2 database
databases:
  kraken2: Create
  bracken: Create
  humann2_bowtie2: Create
  humann2_diamond: Create

#-- software parameters --#
params:
  bracken_build_kmer: 35
  bracken_build_read_lens:
    - 100
    - 150
  prodigal: ""
  diamond_db: /ebio/abt3_projects/databases_no-backup/humann2/uniref50/uniref50_annotated.1.1.dmnd
  diamond_db_to_mem: True
  diamond: --evalue 1e-3 --sensitive --max-target-seqs 20 --block-size 3 --index-chunks 2
  vsearch: --id 0.97 --strand both --qmask none --fasta_width 0

#-- snakemake pipeline --#
pipeline:
  snakemake_folder: ./
  script_folder: ./bin/scripts/
  temp_folder: /tmp/global2/        # your username will be added automatically to this path
